"""The demonstration dashboard (SPEC section 43).

A lightweight Streamlit front end over the artifacts the pipeline has already
written. Six pages: city overview, predictions, patterns, data health, model
evolution, and the three-arm experiment.

**It recomputes nothing.** Every figure is read from a stored artifact, through
the same :class:`~urbansense.api.store.ArtifactStore` the API uses. A dashboard
that retrained a model to draw a chart would make the picture disagree with the
reports, and would take minutes per page load.

The package is split so that the data layer is testable without launching
Streamlit:

:mod:`urbansense.dashboard.loaders`
    Where data comes from -- the stored files directly, or the read-only API
    over HTTP. One protocol, two backends.

:mod:`urbansense.dashboard.views`
    What each page says: artifacts in, plain dicts and lists out.

:mod:`urbansense.dashboard.app`
    How it looks. **The only module that imports streamlit.**

Two things every page carries. **Source-specific views come before the unified
one** (SPEC section 20), so a reader can always see which stream a number came
from -- a healthy total hides an unhealthy feed. And **everything on screen is
synthetic**: generated by this repository with known planted ground truth, not
measured in a city and not a forecast for one.
"""

from urbansense.dashboard.loaders import (
    ApiLoader,
    ArtifactLoader,
    DashboardData,
    build_loader,
)
from urbansense.dashboard.views import SYNTHETIC_BANNER, Panel

__all__ = [
    "SYNTHETIC_BANNER",
    "ApiLoader",
    "ArtifactLoader",
    "DashboardData",
    "Panel",
    "build_loader",
]
